syntax = "proto3";

package notification.v1;

option go_package = "github.com/ramisoul84/kfc-notification/gen/notification/v1;notificationv1";

import "google/protobuf/timestamp.proto";

service NotificationService {
  rpc SendWelcomeEmail(SendWelcomeEmailRequest) returns (SendWelcomeEmailResponse);
}

// ─────────── Welcome Email ───────────

message SendWelcomeEmailRequest {
  string to               = 1;
  string email            = 2;
  string role_name        = 3;
  string initial_password = 4;
  string restaurant_id    = 5;
  string region_id        = 6;
}

message SendWelcomeEmailResponse {
  bool   success         = 1;
  string message         = 2;
  string notification_id = 3;
  google.protobuf.Timestamp sent_at = 4;
}